version: '3.4'

services:  
  identityserver:
    container_name: geekshopping-identity
    environment:
        - aspnetcore_environment=development
        - aspnetcore_urls=https://+:8001;http://+:8000
    ports:
        - "8000:80"
        - "8001:443"
    expose:
        - "8000"
        - "8001"
    volumes:
        - ${appdata}/microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        - ${appdata}/asp.net/https:/root/.aspnet/https:ro
    networks:
        - local

  productapi:
    container_name: geekshopping-product-api
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=https://+:5001;http://+:5000
    ports:
       - "5001:5001"
       - "5000:5000"
    expose:
        - "5000"
        - "5001"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
        - local 
    depends_on:
        - identityserver
        - mssql

  web:
    container_name: geekshopping-web
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:8081;http://+:8080
    ports:
        - "8080:8080"
        - "8081:8081"
    expose:
        - "8080"
        - "8081"        
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
        - local
    depends_on:
        - productapi
      
        
volumes:
  mssql_data:
    driver: local       

networks:
    local:
        name: localhost
        driver: bridge           
